version: "3.3"
services:
  nginx:
    image: nginx
    container_name: web_server
    ports:
        - 80:80
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./logs:/var/log/nginx
