---

- name: copy nginx.config file to remote server
  template:
      src: /etc/ansible/roles/nginx/templates/nginx.conf
      dest: /var/apps/nginx_swagger/
      follow: yes

- name: copy docker-compose yml
  ansible.builtin.copy:
      src: /etc/ansible/roles/nginx/files/docker-compose.yml
      dest: /var/apps/nginx_swagger/
      follow: yes

- name: run docker-compose.yml
  docker_compose:
      project_src: /var/apps/nginx_swagger
