---

- name: Install aptitude (same as apt in ubuntu)
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Install required system packages 
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: download GPG public key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository into /etc/apt/sources.list
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Install docker-compose  
  apt: update_cache=yes name=docker-compose state=latest
